"""empty message

Revision ID: 890864b362f3
Revises: d1e99ca05b67
Create Date: 2017-05-22 16:24:03.872323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890864b362f3'
down_revision = 'd1e99ca05b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_text', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
